### ISSUE TITLE
父应用无法感知子应用路由切换

### ISSUE THREAD

**Issue by dream2023** [hql7/wl-micro-frontends#12]
https://github.com/umijs/qiankun/issues/339

这个是qiankun的问题，只是想请教一下大神有没有遇到过，怎么解决的

**Comment by hql7** [comment]
没试过，但是在子应用路由守卫通过事件通知父应用如何



在 2020-03-26 15:36:23，"张超杰" <notifications@github.com> 写道：

umijs/qiankun#339

这个是qiankun的问题，只是想请教一下大神有没有遇到过，怎么解决的
