### ISSUE TITLE
独立访问子应用时在非根路由刷新问题

### ISSUE THREAD

**Issue by fyzwjd** [hql7/wl-micro-frontends#21]
拉下代码后，安装好依赖运行，直接访问子应用http://localhost:6652 正常，进入about路由也正常，刷新页面后页面加载失败：
http://localhost:6652/about

![image](https://user-images.githubusercontent.com/8544695/79335773-26e96880-7f55-11ea-8d05-0cc7ca34a0c5.png)

**Comment by yu530feng** [comment]
因为你启动了主应用。注意理解qiankun的原理
