### ISSUE TITLE
subapp-ui 抽离出去之后 提示application 'subapp-ui' died in status LOADING_SOURCE_CODE: Failed to fetch

### ISSUE THREAD

**Issue by matianqing** [hql7/wl-micro-frontends#30]
single-spa.min.js?25a2:2 Uncaught TypeError: application 'subapp-ui' died in status LOADING_SOURCE_CODE: Failed to fetch
![image](https://user-images.githubusercontent.com/18375879/82735959-7e4ed580-9d58-11ea-8818-2720172f0201.png)
场景：“我将 subapp-ui 单独抽出去放在了git ”
问题：如上，启动后提示这个，subapp-ui 此工程已经抽离出去，已经不在【WL-MICRO-FRONTENDS】此文件结构目录下

**Comment by hql7** [comment]
放在哪里无所谓，在运行并且地址和主应用注册所写地址一致即可

发自我的iPhone

**Comment by matianqing** [comment]
子应用 如果单独抽离出去，独立运行的时候想 看和主框架 的效果 怎么办

**Comment by hql7** [comment]
和基座一起运行


发自我的iPhone

**Comment by matianqing** [comment]
谢谢你的回复。了解



---原始邮件---
发件人: "Bug制作员"<notifications@github.com&gt;
发送时间: 2020年5月24日(周日) 晚上11:28
收件人: "hql7/wl-micro-frontends"<wl-micro-frontends@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"matianqing"<476839884@qq.com&gt;;
主题: Re: [hql7/wl-micro-frontends] subapp-ui 抽离出去之后 提示application 'subapp-ui' died in status LOADING_SOURCE_CODE: Failed to fetch (#30)




 和基座一起运行
 
 
 发自我的iPhone
 
 &gt; 在 2020年5月24日，22:54，matianqing <notifications@github.com&gt; 写道：
 &gt; 
 &gt; ﻿
 &gt; 子应用 如果单独抽离出去，独立运行的时候想 看和主框架 的效果 怎么办
 &gt; 
 &gt; —
 &gt; You are receiving this because you commented.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
