### ISSUE TITLE
在qiankun官方文档的registerMicroApps的apps参数中接收container参数，为何此处是render呢？

### ISSUE THREAD

**Issue by sohoorc** [hql7/wl-micro-frontends#42]
在qiankun官方文档的registerMicroApps的apps参数中接收container参数，为何此处是render呢？有点不理解为何改了参数名称依旧能够正常运行，求指教。

qiankun文档：

```
{
      name: 'app1',
      entry: '//localhost:8080',
      container: '#container',
      activeRule: '/react',
      props: {
        name: 'kuitos',
      }
```

```
{
                name: i.module,
                entry: isDev ? i.devEntry : i.depEntry,
                render,
                activeRule: genActiveRule(i.routerBase),
                props: { ...msg, ROUTES: i.children, routerBase: i.routerBase }
            }
```

**Comment by hql7** [comment]
目前qiankun文档是2.0，此项目是在qiankun早期1.0版本写的，2.0版本见wl-mfe



在 2020-07-27 17:44:54，"Weitian Gan" <notifications@github.com> 写道：

在qiankun官方文档的registerMicroApps的apps参数中接收container参数，为何此处是render呢？有点不理解为何改了参数名称依旧能够正常运行，求指教。

qiankun文档：

{

      name: 'app1',

      entry: '//localhost:8080',

      container: '#container',

      activeRule: '/react',

      props: {

        name: 'kuitos',

      }


{

                name: i.module,

                entry: isDev ? i.devEntry : i.depEntry,

                render,

                activeRule: genActiveRule(i.routerBase),

                props: { ...msg, ROUTES: i.children, routerBase: i.routerBase }

            }

**Comment by sohoorc** [comment]
> 目前qiankun文档是2.0，此项目是在qiankun早期1.0版本写的，2.0版本见wl-mfe 在 2020-07-27 17:44:54，"Weitian Gan" <notifications@github.com> 写道： 在qiankun官方文档的registerMicroApps的apps参数中接收container参数，为何此处是render呢？有点不理解为何改了参数名称依旧能够正常运行，求指教。 qiankun文档： { name: 'app1', entry: '//localhost:8080', container: '#container', activeRule: '/react', props: { name: 'kuitos', } { name: i.module, entry: isDev ? i.devEntry : i.depEntry, render, activeRule: genActiveRule(i.routerBase), props: { ...msg, ROUTES: i.children, routerBase: i.routerBase } } — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢，了解了。
