### ISSUE TITLE
生产环境部署后，F5刷新页面，nginx 404

### ISSUE THREAD

**Issue by nihaoaWO** [hql7/wl-micro-frontends#57]
现项目打包后使用nginx部署，可以访问，但是刷新页面时，会出现404，原因应该是他直接从子应用开始加载，我观察了您提供的在线地址，是支持刷新的，麻烦提供一下思路

**Comment by hql7** [comment]
404一般是路由history模式的问题



在 2020-09-21 19:57:21，"nihaoaWO" <notifications@github.com> 写道：

现项目打包后使用nginx部署，可以访问，但是刷新页面时，会出现404，原因应该是他直接从子应用开始加载，我观察了您提供的在线地址，是支持刷新的，麻烦提供一下思路

**Comment by nihaoaWO** [comment]
已经解决了，谢谢

**Comment by Shangri-GitHub** [comment]
@nihaoaWO  如何解决的，提供下思路。谢谢

**Comment by hql7** [comment]
见 vueRouter histry模式nginx配置










在 2020-11-03 18:19:04，"Shangri-GitHub" <notifications@github.com> 写道：

@nihaoaWO 如何解决的，提供下思路。谢谢
